Added new branch 2013.10

diff --git a/dts/Makefile b/dts/Makefile
--- a/dts/Makefile
+++ b/dts/Makefile
@@ -1,66 +1,92 @@
-# SPDX-License-Identifier: GPL-2.0+
 #
 # Copyright (c) 2011 The Chromium OS Authors.
+#
+# SPDX-License-Identifier:	GPL-2.0+
+#
 
 # This Makefile builds the internal U-Boot fdt if CONFIG_OF_CONTROL is
 # enabled. See doc/README.fdt-control for more details.
 
-DEVICE_TREE ?= $(CONFIG_DEFAULT_DEVICE_TREE:"%"=%)
+include $(TOPDIR)/config.mk
+
+LIB	= $(obj)libdts.o
+
 ifeq ($(DEVICE_TREE),)
-DEVICE_TREE := unset
+$(if $(CONFIG_DEFAULT_DEVICE_TREE),,\
+$(error Please define CONFIG_DEFAULT_DEVICE_TREE in your board header file))
+DEVICE_TREE = $(subst ",,$(CONFIG_DEFAULT_DEVICE_TREE))
 endif
 
-ifneq ($(EXT_DTB),)
-DTB := $(EXT_DTB)
-else
-DTB := arch/$(ARCH)/dts/$(DEVICE_TREE).dtb
-endif
+DTS_INCDIRS =  $(SRCTREE)/board/$(VENDOR)/$(BOARD)/dts
+DTS_INCDIRS += $(SRCTREE)/board/$(VENDOR)/dts
+DTS_INCDIRS += $(SRCTREE)/arch/$(ARCH)/dts
 
-$(obj)/dt-$(SPL_NAME).dtb: dts/dt.dtb $(objtree)/tools/fdtgrep FORCE
-	mkdir -p $(dir $@)
-	$(call if_changed,fdtgrep)
+DTS_CPPFLAGS := -x assembler-with-cpp -undef -D__DTS__ \
+		-nostdinc $(addprefix -I,$(DTS_INCDIRS))
 
-ifeq ($(CONFIG_OF_DTB_PROPS_REMOVE),y)
-$(obj)/dt.dtb: $(DTB) $(objtree)/tools/fdtgrep FORCE
-	$(call if_changed,fdt_rm_props)
-else
-$(obj)/dt.dtb: $(DTB) FORCE
-	$(call if_changed,shipped)
-endif
+DTC_FLAGS := -R 4 -p 0x1000 \
+	$(addprefix -i ,$(DTS_INCDIRS))
 
-targets += dt.dtb
+all:	$(obj).depend $(LIB)
 
-$(DTB): arch-dtbs
-	$(Q)test -e $@ || (						\
-	echo >&2;							\
-	echo >&2 "Device Tree Source ($@) is not correctly specified.";	\
-	echo >&2 "Please define 'CONFIG_DEFAULT_DEVICE_TREE'";		\
-	echo >&2 "or build with 'DEVICE_TREE=<device_tree>' argument";	\
-	echo >&2;							\
-	/bin/false)
+# Use a constant name for this so we can access it from C code.
+# objcopy doesn't seem to allow us to set the symbol name independently of
+# the filename.
+DT_BIN	:= $(obj)dt.dtb
 
-PHONY += arch-dtbs
-arch-dtbs:
-	$(Q)$(MAKE) $(build)=arch/$(ARCH)/dts dtbs
+$(DT_BIN): $(TOPDIR)/board/$(VENDOR)/dts/$(DEVICE_TREE).dts
+	$(CPP) $(DTS_CPPFLAGS) $< -o $(DT_BIN).dts.tmp
+	$(DTC) $(DTC_FLAGS) -O dtb -o ${DT_BIN} $(DT_BIN).dts.tmp
 
-ifeq ($(CONFIG_SPL_BUILD),y)
-obj-$(CONFIG_OF_EMBED) := dt-spl.dtb.o
-# support "out-of-tree" build for dtb-spl
-$(obj)/dt-spl.dtb.o: $(obj)/dt-spl.dtb.S FORCE
-	$(call if_changed_dep,as_o_S)
-else
-obj-$(CONFIG_OF_EMBED) := dt.dtb.o
-endif
+process_lds = \
+	$(1) | sed -r -n 's/^OUTPUT_$(2)[ ("]*([^")]*).*/\1/p'
 
-# Target for U-Boot proper
-dtbs: $(obj)/dt.dtb
-	@:
+# Run the compiler and get the link script from the linker
+GET_LDS = $(CC) $(CFLAGS) $(LDFLAGS) -Wl,--verbose 2>&1
 
-# Target for SPL/TPL
-spl_dtbs: $(obj)/dt-$(SPL_NAME).dtb
-	@:
+$(obj)dt.o: $(DT_BIN)
+	# We want the output format and arch.
+	# We also hope to win a prize for ugliest Makefile / shell interaction
+	# We look in the LDSCRIPT first.
+	# Then try the linker which should give us the answer.
+	# Then check it worked.
+	[ -n "$(LDSCRIPT)" ] && \
+		oformat=`$(call process_lds,cat $(LDSCRIPT),FORMAT)` && \
+		oarch=`$(call process_lds,cat $(LDSCRIPT),ARCH)` ;\
+	\
+	[ -z $${oformat} ] && \
+		oformat=`$(call process_lds,$(GET_LDS),FORMAT)` ;\
+	[ -z $${oarch} ] && \
+		oarch=`$(call process_lds,$(GET_LDS),ARCH)` ;\
+	\
+	[ -z $${oformat} ] && \
+		echo "Cannot read OUTPUT_FORMAT from lds file $(LDSCRIPT)" && \
+		exit 1 || true ;\
+	[ -z $${oarch} ] && \
+		echo "Cannot read OUTPUT_ARCH from lds file $(LDSCRIPT)" && \
+		exit 1 || true ;\
+	\
+	cd $(dir ${DT_BIN}) && \
+	$(OBJCOPY) -I binary -O $${oformat} -B $${oarch} \
+		$(notdir ${DT_BIN}) $@
+	rm $(DT_BIN)
 
-clean-files := dt.dtb.S
+OBJS-$(CONFIG_OF_EMBED)	:= dt.o
 
-# Let clean descend into dts directories
-subdir- += ../arch/arm/dts ../arch/microblaze/dts ../arch/mips/dts ../arch/sandbox/dts ../arch/x86/dts ../arch/powerpc/dts ../arch/riscv/dts
+COBJS	:= $(OBJS-y)
+
+OBJS	:= $(addprefix $(obj),$(COBJS))
+
+binary:	$(DT_BIN)
+
+$(LIB):	$(OBJS) $(DTB)
+	$(call cmd_link_o_target, $(OBJS))
+
+#########################################################################
+
+# defines $(obj).depend target
+include $(SRCTREE)/rules.mk
+
+sinclude $(obj).depend
+
+#########################################################################
